
import Herosection from "@/app/components/Herosection";

export const metadata = {
    title: "About page",
    description: "Generated by create next app",
  };

const About = () => {
    return (
        <Herosection title={"OUR STORY"} imageUrl ={"/about1.svg"} />
    );
};

export default About;